name: CI Build - Click

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ðŸŒŠ Get the source code of this repositorie...
        uses: actions/checkout@v3

      - name: ðŸŒŠ Get variable configuration...
        run: |
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date +%s)" >> $GITHUB_ENV

      - name: ðŸŒŠ Configuration Environmentâ€Œâ€Œ...
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash env.sh

      - name: ðŸŒŠ Start building...
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash build.sh
          sudo chmod -R 0777 ./*
          echo "RELEASE_NAME=$(cat "$GITHUB_WORKSPACE/out/RELEASETITLE.txt")" >> $GITHUB_ENV
          echo "${{ env.RELEASE_NAME }}"
          
      - name: ðŸŒŠ Upload to Releaseâ€Œâ€Œ...
        uses: ncipollo/release-action@main
        with:
          artifacts: "${{ github.workspace }}/out/*"
          name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.BUILD_TIME }}
          bodyFile: "${{ github.workspace }}/out/RELEASE.md"
          token: ${{ secrets.GITHUB_TOKEN }}
