name: CI Build - Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ðŸŒŠ Get the source code of this repositorie...
        uses: actions/checkout@main

      - name: ðŸŒŠ Configuration Environmentâ€Œâ€Œ...
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash env.sh

      - name: ðŸŒŠ Start building...
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash build.sh
          sudo chmod -R 0777 ./*
          
      - name: ðŸŒŠ Get variable configuration...
        run: |
          echo "KERNELSU_VERSION=$(cat "$GITHUB_WORKSPACE/out/KSU_VERSION.txt")" >> $GITHUB_ENV
          echo "KERNEL_VERSION=$(cat "$GITHUB_WORKSPACE/out/KERNEL_VERSION.txt")" >> $GITHUB_ENV
          echo "${{ env.KERNELSU_VERSION }}"
          echo "${{ env.KERNEL_VERSION }}"

      - name: ðŸŒŠ Upload to Releaseâ€Œâ€Œ...
        uses: ncipollo/release-action@main
        with:
          artifacts: "${{ github.workspace }}/out/*"
          name: KernelSU-${{ env.KERNELSU_VERSION }}-${{ env.KERNEL_VERSION }}-${{ github.run_id }}
          tag: ${{ github.run_id }}
          bodyFile: "${{ github.workspace }}/out/RELEASE.md"
          token: ${{ secrets.TOKEN_MOCHENYA }}
