name: CI Build - Cron

on:
  schedule:
    - cron: '0 17 * * *' # ä¸Šæµ·æ—¶é—´å‡Œæ™¨1ç‚¹è§¦å‘
    - cron: '0 4 * * *'  # ä¸Šæµ·æ—¶é—´ä¸­åˆ12ç‚¹è§¦å‘
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ðŸŒŠ Get the source code of this repositorie...
        uses: actions/checkout@main

      - name: ðŸŒŠ Check for redundancy...
        id: check
        run: |
          cd $GITHUB_WORKSPACE
          bash -x check.sh || echo check=0 >> "$GITHUB_OUTPUT"

      - name: ðŸŒŠ Configuration Environmentâ€Œâ€Œ...
        if: ${{ steps.check.outputs.check != '0' }}
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash env.sh

      - name: ðŸŒŠ Start building...
        if: ${{ steps.check.outputs.check != '0' }}
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash build.sh
          sudo chmod -R 0777 ./*
          
      - name: ðŸŒŠ Get variable configuration...
        if: ${{ steps.check.outputs.check != '0' }}
        run: |
          echo "KERNELSU_VERSION=$(cat "$GITHUB_WORKSPACE/out/KSU_VERSION.txt")" >> $GITHUB_ENV
          echo "KERNEL_VERSION=$(cat "$GITHUB_WORKSPACE/out/KERNEL_VERSION.txt")" >> $GITHUB_ENV
          echo "${{ env.KERNELSU_VERSION }}"
          echo "${{ env.KERNEL_VERSION }}"

      - name: ðŸŒŠ Upload to Releaseâ€Œâ€Œ...
        if: ${{ steps.check.outputs.check != '0' }}
        uses: ncipollo/release-action@main
        with:
          artifacts: "${{ github.workspace }}/out/*"
          name: KernelSU-${{ env.KERNELSU_VERSION }}-${{ env.KERNEL_VERSION }}-${{ github.run_id }}
          tag: ${{ github.run_id }}
          bodyFile: "${{ github.workspace }}/out/RELEASE.md"
          token: ${{ secrets.GITHUB_TOKEN }}
